import { ops } from './ops';
import { compilePlan } from './compile';

const { say, status, addTask, task, metricSet, metricAdd, browse, bstep, check, recovery } = ops;

// A step: wait `delay` ms (at 1x), then apply every op in order.
// Tasks carry a scripted `why` ({ objective, reason }) that the explainability
// drawer shows. It is authored with the demo, not generated by a model.
const s = (delay, ...fns) => ({ delay, run: (m) => fns.reduce((acc, f) => f(acc), m) });

// The hero mission is hand-authored. Every other mission is compiled from the
// plan the planner produced for its goal.
export function compileScript(plan) {
  return plan.kind === 'hero' ? registrations(plan.goal) : compilePlan(plan);
}

// ---------------------------------------------------------------------------
// Hero demo: "Get 100 registrations for our hackathon"

export const HERO_TASKS = [
  {
    id: 't1', title: 'Research the audience', agent: 'research', deps: [],
    why: { objective: 'Know who to invite, and when.', reason: 'A target of 100 is only reachable if outreach starts from a real audience instead of guesses.' },
  },
  {
    id: 't2', title: 'Build registration form', agent: 'browser', deps: ['t1'],
    why: { objective: 'Give every invitee one place to sign up.', reason: 'Every outreach channel needs a live link before anything is sent.' },
  },
  {
    id: 't3', title: 'Draft the invite email', agent: 'execution', deps: ['t1'],
    why: { objective: 'Turn the research into an invite people act on.', reason: 'Past attendees are the warmest audience, and email reaches them directly.' },
  },
  {
    id: 't4', title: 'Review the draft', agent: 'critic', deps: ['t3'],
    why: { objective: 'Raise the invite’s conversion before it goes out.', reason: 'A sent email can’t be improved. Reviewing first is cheap.' },
  },
  {
    id: 't5', title: 'Email 480 past attendees', agent: 'execution', deps: ['t2', 't4'], gated: true,
    why: { objective: 'Reach every past attendee.', reason: 'Past attendees convert best, but emailing people outside the team needs your sign-off.' },
  },
  {
    id: 't6', title: 'Post in community channels', agent: 'browser', deps: ['t2'],
    why: { objective: 'Reach students who have never attended.', reason: 'Email only covers past attendees. The clubs’ Discord servers reach new people.' },
  },
  {
    id: 't7', title: 'Verify 100 real sign-ups', agent: 'verification', deps: ['t5', 't6'],
    why: { objective: 'Confirm the target with real, unique sign-ups.', reason: 'Raw form responses include duplicates and bad emails. Only verified sign-ups count toward the goal.' },
  },
];

function registrations(goal) {
  const tasks = HERO_TASKS;

  const payload = {
    from: 'events@hackos.dev',
    recipients: 480,
    audience: 'past attendees',
    subject: '48 hours, $5,000 in prizes. Registration closes Friday',
    body:
      "Hi there,\n\nHackOS 2026 is back on Oct 18–19. Build anything in 48 hours, with $5,000 in prizes and mentors from top startups.\n\nRegister in 30 seconds: forms.example.com/hackos-2026\n\nSee you there,\nThe HackOS team",
  };

  // The send uses whatever you approved: edit the recipient count and every
  // number downstream follows from it.
  const approve = ({ edited, payload: p }) => {
    const n = p.recipients;
    const share = (x) => Math.round((x * n) / 480);
    return [
      s(600, say('approval', edited ? `Approved with your edits (${n} recipients). Resuming.` : 'Approved. Resuming the mission.', 'approval'),
        status('running'), task('t5', { status: 'running', title: `Email ${n} past attendees` })),
      s(1400, say('execution', `Simulating the send to ${n} recipients in batches of 60, as a real send would to stay under spam limits.`)),
      s(1600, say('execution', `Outreach action simulated successfully: ${n} of ${n} invites delivered in the simulation, ${Math.max(1, share(3))} bounced.`, 'action'), task('t5', { status: 'done' }), metricSet(share(18))),
      s(1200, metricSet(share(41)), say('execution', `${share(41)} simulated registrations from the first wave.`)),
    ];
  };

  const reject = () => [
    s(600, say('approval', 'Rejected. No emails will be sent.', 'approval'), status('running'), task('t5', { status: 'skipped' })),
    s(1300, say('planner', 'Re-planning without email: asking the 3 club leads to share the form instead.', 'plan'),
      addTask({
        id: 't5b', title: 'Ask club leads to share', agent: 'execution', deps: ['t2'], status: 'running',
        why: { objective: 'Reach past attendees without sending email.', reason: 'You rejected the email, so the plan routes the invite through the three club leads instead.' },
      }),
      task('t7', (t) => ({ deps: [...t.deps.filter((d) => d !== 't5'), 't5b'] }))),
    s(1800, say('execution', 'Simulated: all 3 club leads shared the form in their groups.', 'action'), task('t5b', { status: 'done' }), metricSet(29)),
  ];

  return {
    metric: { label: 'Verified registrations', current: 0, target: 100 },
    script: [
      s(500, say('system', `Mission received: “${goal}”`, 'system')),
      s(1300, say('planner', 'Reading the goal. Success means 100 verified, unique registrations.')),
      ...tasks.map((t) => s(320, addTask(t))),
      s(700, say('planner', 'Plan ready: 7 tasks. The form and the outreach will run in parallel.', 'plan'), status('running')),
      s(800, task('t1', { status: 'running' }), say('execution', 'Research, you’re up. Who should we invite?')),
      s(1700, say('research', 'In the demo data: 480 past attendees from last year’s sign-up sheet and 3 student clubs with active Discord servers.')),
      s(1300, say('research', 'Engagement peaks Tuesday at 6 PM. Similar events convert 20–25% of invites.'), task('t1', { status: 'done' })),
      s(700, task('t2', { status: 'running' }), task('t3', { status: 'running' }),
        say('execution', 'Browser, build the form. I’ll draft the invite in parallel.')),
      s(900, browse({ url: 'https://forms.example.com/new', title: 'Form builder (simulated)' }), bstep('Opened the form builder')),
      s(1000, bstep('Created form “HackOS 2026 Registration”')),
      s(1000, bstep('Added fields: name, email, college, team size')),
      s(1000, bstep('Turned on confirmation emails')),
      s(900, browse({ url: 'https://forms.example.com/hackos-2026' }), bstep('Published the form'),
        say('browser', 'Registration form creation simulated. Demo link: forms.example.com/hackos-2026.', 'action'), task('t2', { status: 'done' })),
      s(900, say('execution', 'Draft ready: “You’re invited to HackOS 2026”.'), task('t3', { status: 'done' }), task('t4', { status: 'running' })),
      s(1500, say('critic', 'The subject line is generic and there’s no deadline. Lead with the prize and “closes Friday”.', 'critique')),
      s(1200, say('execution', `Revised subject: “${payload.subject}”.`), task('t4', { status: 'done' })),
      s(900, task('t5', { status: 'awaiting' }),
        say('approval', 'This would email 480 people from events@hackos.dev. Pausing for your approval.', 'approval')),
      {
        delay: 300,
        approval: {
          title: 'Send invite email to 480 people',
          agent: 'approval',
          risk: 'medium',
          category: 'External communication',
          reason: 'Sends email on your behalf to people outside your team.',
          payload,
        },
        approve,
        reject,
      },
      // Shared tail. The failure below happens on every run: recovery is the point of the demo.
      s(800, task('t6', { status: 'running' }),
        browse({ url: 'https://discord.com/channels/hackclub/events', title: 'Discord · #events (simulated)' }),
        bstep('Opened #events in the Hack Club server')),
      s(1000, bstep('Typed the announcement with the form link')),
      s(1200, bstep('Post rejected: “New members can’t post links”', 'failed'),
        task('t6', { status: 'failed' }), status('recovering'),
        say('browser', 'Discord rejected the post: new members can’t share links.', 'failure'),
        recovery({ id: 'r1', task: 'Post in community channels', error: 'Discord blocked the post. New members can’t share links.', status: 'diagnosing' })),
      s(1300, say('recovery', 'Failure detected in “Post in community channels”. Diagnosing…', 'recovery')),
      s(1700, recovery({ id: 'r1', diagnosis: 'This server blocks links from accounts under 7 days old. Retrying the same post will fail again.', status: 'replanning' }),
        say('recovery', 'Root cause: this server blocks links from accounts newer than 7 days. A plain retry won’t work.', 'recovery')),
      s(1700, recovery({ id: 'r1', plan: 'Post the invite as an image with a QR code (no link), then ask a moderator to pin it.', status: 'retrying' }),
        say('recovery', 'New plan: post the invite as an image with a QR code, then ask a moderator to pin it.', 'recovery')),
      s(900, say('planner', 'Plan updated: “Post in community channels” now posts a QR-code image, not a link. Handing back to Execution.', 'plan')),
      s(700, say('execution', 'Resuming the community post with the new approach.', 'action'), task('t6', { status: 'running' })),
      s(1000, say('critic', 'Good call. An image stands out more in the feed anyway.', 'critique'),
        bstep('Generated an invite image with a QR code')),
      s(1100, bstep('Posted the image in #events'), bstep('Asked @mod-riya to pin it')),
      s(1300, bstep('Post pinned by a moderator'), recovery({ id: 'r1', status: 'resolved' }), status('running'),
        task('t6', { status: 'done' }), metricAdd(35),
        say('recovery', 'Recovered. The simulated post is up and pinned. Mission back on track.', 'recovered')),
      s(1500, metricAdd(22), say('execution', (m) => `${m.metric.current} simulated registrations. The Discord post is driving sign-ups.`)),
      s(900, task('t7', { status: 'running' }), say('verification', 'Checking every response against the goal…')),
      s(1200, check((m) => `${m.metric.current} form responses received`)),
      s(1000, check('6 duplicate entries removed', 'warn'), check('2 invalid emails removed', 'warn'), metricAdd(-8)),
      s(1200, say('verification', (m) => `Only ${m.metric.current} valid registrations. That’s below the target of 100.`, 'failure'),
        check((m) => `${m.metric.current} verified, short of 100`, 'failed'), task('t7', { status: 'failed' })),
      s(1400, say('planner', 'Adding a follow-up: remind the 60 people who opened the form but didn’t submit.', 'plan'),
        addTask({
          id: 't8', title: 'Remind unfinished sign-ups', agent: 'execution', deps: ['t7'], status: 'running',
          why: { objective: 'Close the gap to 100.', reason: 'Verification found too few real sign-ups. People who started the form but didn’t finish are the cheapest to convert.' },
        })),
      s(1800, say('execution', 'Reminder simulated for the 60 people who started the form.', 'action'), task('t8', { status: 'done' }), metricSet(104)),
      s(1300, task('t7', { status: 'running' }), check('Re-counted after the reminder')),
      s(1200, check('104 verified registrations (target: 100)'), task('t7', { status: 'done' }),
        say('verification', 'Verified: 104 unique, valid registrations in the simulation. Target reached.', 'verified')),
      s(800, status('completed'), say('system', 'Simulated mission target reached: 104 of 100 registrations.', 'complete')),
    ],
  };
}
