"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-29 13:15:52.868781
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tool',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('capability', sa.String(length=40), nullable=False),
    sa.Column('risk', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('integration', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    with op.batch_alter_table('tool', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tool_capability'), ['capability'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('integration',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('encrypted_token', sa.LargeBinary(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider')
    )
    with op.batch_alter_table('integration', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integration_user_id'), ['user_id'], unique=False)

    op.create_table('mission',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('goal', sa.String(length=500), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('plan_json', sa.JSON(), nullable=False),
    sa.Column('metric_label', sa.String(length=120), nullable=False),
    sa.Column('metric_current', sa.Integer(), nullable=False),
    sa.Column('metric_target', sa.Integer(), nullable=False),
    sa.Column('budget_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mission_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_mission_user_id'), ['user_id'], unique=False)

    op.create_table('mission_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mission_id', sa.String(length=32), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('agent', sa.String(length=40), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['mission.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mission_id', 'seq')
    )
    with op.batch_alter_table('mission_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mission_event_mission_id'), ['mission_id'], unique=False)

    op.create_table('mission_intent',
    sa.Column('mission_id', sa.String(length=32), nullable=False),
    sa.Column('objective', sa.String(length=500), nullable=False),
    sa.Column('domain', sa.String(length=40), nullable=False),
    sa.Column('desired_outcome', sa.String(length=300), nullable=False),
    sa.Column('intent_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['mission.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('mission_id')
    )
    op.create_table('task',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('mission_id', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('capability', sa.String(length=40), nullable=True),
    sa.Column('agent', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('gated', sa.Boolean(), nullable=False),
    sa.Column('criterion', sa.String(length=300), nullable=True),
    sa.Column('replaced_by_key', sa.String(length=40), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['mission.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mission_id', 'key')
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_mission_id'), ['mission_id'], unique=False)

    op.create_table('agent_execution',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('mission_id', sa.String(length=32), nullable=False),
    sa.Column('task_id', sa.String(length=32), nullable=True),
    sa.Column('agent_id', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['mission_id'], ['mission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_execution', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_execution_mission_id'), ['mission_id'], unique=False)

    op.create_table('approval',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('mission_id', sa.String(length=32), nullable=False),
    sa.Column('task_id', sa.String(length=32), nullable=True),
    sa.Column('tool_name', sa.String(length=80), nullable=True),
    sa.Column('risk', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('original_payload_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['mission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_mission_id'), ['mission_id'], unique=False)

    op.create_table('recovery_attempt',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('mission_id', sa.String(length=32), nullable=False),
    sa.Column('task_id', sa.String(length=32), nullable=True),
    sa.Column('failure_class', sa.String(length=40), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=False),
    sa.Column('strategy', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['mission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recovery_attempt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recovery_attempt_mission_id'), ['mission_id'], unique=False)

    op.create_table('task_dependency',
    sa.Column('task_id', sa.String(length=32), nullable=False),
    sa.Column('depends_on_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_id'], ['task.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'depends_on_id')
    )
    op.create_table('tool_execution',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('mission_id', sa.String(length=32), nullable=False),
    sa.Column('task_id', sa.String(length=32), nullable=True),
    sa.Column('tool_name', sa.String(length=80), nullable=False),
    sa.Column('risk', sa.String(length=10), nullable=False),
    sa.Column('input_json', sa.JSON(), nullable=False),
    sa.Column('output_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_class', sa.String(length=40), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['mission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tool_name'], ['tool.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tool_execution', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tool_execution_mission_id'), ['mission_id'], unique=False)

    op.create_table('evidence',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('mission_id', sa.String(length=32), nullable=False),
    sa.Column('task_id', sa.String(length=32), nullable=True),
    sa.Column('tool_execution_id', sa.String(length=32), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('reference_id', sa.String(length=200), nullable=True),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['mission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tool_execution_id'], ['tool_execution.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_mission_id'), ['mission_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_mission_id'))

    op.drop_table('evidence')
    with op.batch_alter_table('tool_execution', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tool_execution_mission_id'))

    op.drop_table('tool_execution')
    op.drop_table('task_dependency')
    with op.batch_alter_table('recovery_attempt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recovery_attempt_mission_id'))

    op.drop_table('recovery_attempt')
    with op.batch_alter_table('approval', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_mission_id'))

    op.drop_table('approval')
    with op.batch_alter_table('agent_execution', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_execution_mission_id'))

    op.drop_table('agent_execution')
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_mission_id'))

    op.drop_table('task')
    op.drop_table('mission_intent')
    with op.batch_alter_table('mission_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mission_event_mission_id'))

    op.drop_table('mission_event')
    with op.batch_alter_table('mission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mission_user_id'))
        batch_op.drop_index(batch_op.f('ix_mission_created_at'))

    op.drop_table('mission')
    with op.batch_alter_table('integration', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integration_user_id'))

    op.drop_table('integration')
    op.drop_table('user')
    with op.batch_alter_table('tool', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tool_capability'))

    op.drop_table('tool')
    op.drop_table('agent')
    # ### end Alembic commands ###
