"""mission source

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-29 17:08:09.445109
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=10), server_default='typed', nullable=False))
        batch_op.add_column(sa.Column('template_id', sa.String(length=60), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mission', schema=None) as batch_op:
        batch_op.drop_column('template_id')
        batch_op.drop_column('source')

    # ### end Alembic commands ###
