"""app permissions

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-29 18:52:25.586924
"""
from alembic import op
import sqlalchemy as sa


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_permission',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('app_id', sa.String(length=40), nullable=False),
    sa.Column('action_id', sa.String(length=60), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'app_id', 'action_id')
    )
    with op.batch_alter_table('app_permission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_permission_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('integration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_email', sa.String(length=320), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('integration', schema=None) as batch_op:
        batch_op.drop_column('account_email')

    with op.batch_alter_table('app_permission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_permission_user_id'))

    op.drop_table('app_permission')
    # ### end Alembic commands ###
