"""user preferences

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-30 00:03:14.974362
"""
from alembic import op
import sqlalchemy as sa


revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preference',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('working_days', sa.JSON(), nullable=False),
    sa.Column('work_start', sa.String(length=5), nullable=False),
    sa.Column('work_end', sa.String(length=5), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('signature', sa.Text(), nullable=False),
    sa.Column('tone', sa.String(length=10), nullable=False),
    sa.Column('meeting_length', sa.Integer(), nullable=False),
    sa.Column('groups', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_preference')
    # ### end Alembic commands ###
