"""Add input to Approval

Revision ID: 855d14dfed73
Revises: 0005
Create Date: 2026-09-30 12:53:10.669698
"""
from alembic import op
import sqlalchemy as sa


revision = '855d14dfed73'
down_revision = '0005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approval', schema=None) as batch_op:
        batch_op.add_column(sa.Column('input', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approval', schema=None) as batch_op:
        batch_op.drop_column('input')

    # ### end Alembic commands ###
